### ISSUE TITLE
Private Message Refresh Handling

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_react-native#101]
Private Messages should be refreshed on:

- [ ] App start (or resume)

**Comment by Pinselohrkater** [comment]
Not sure how to describe this, but PM handling is a bit weird.

When you receive a PM:
- You get a notification
- The app still shows "0 new messages", even when you open them, until you force-refresh them by pulling the screen down

We have to do better than that somehow.

**Comment by Requinard** [comment]
basically, PM's are retrieved on the fly and not stored locally. So we'd need to somehow send a signal to refetch the PM's. If we can unmount the Private Message Linker it should do this automatically.
