### ISSUE TITLE
"Non-English" Language Disclaimer on Start Page

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_react-native#65]
On the start page, when the language is NOT english, add a (translatable) language disclaimer box.

![image](https://user-images.githubusercontent.com/13329381/182142393-fb368b7e-36d2-49a9-8d7d-7e09dfc17704.png)

Initial text would be something like: (DE)

"Du nutzt die Applikation in einer anderen Sprache als Englisch. Bitte beachte dass Namen und Texte von sämtlichen dynamischen Inhalten ausschliesslich auf Englisch angezeigt werden."

**Comment by Requinard** [comment]
idk if we should show an entire header icon for this one. It seems better to move it to the settings menu

**Comment by Requinard** [comment]
done by @lukashaertel in the weekend
