### ISSUE TITLE
Proper handling of push messages

### ISSUE THREAD

**Issue by Pinselohrkater** [eurofurence/ef-app_react-native#66]
Expected behavior by message type:

Sync

- [ ] When app is not running: Nothing.
- [ ] When app is running: Run "synchronize" task
  - [ ] (Nice to have) Update content on screen
  

Announcement

- Independent on app state (running, closed):
  - [ ] Show a system notification with
    - [ ] Proper logo (Eurofurence wolf badge)
    - [ ] Title and Message of the announcement
    - [ ] Tapping the notification should...
      - [ ] (at least) ...open the app on the main screen
      - [ ] (at best) ...open the announcement directly

Personal Message

- Independent on app state (running, closed):
  - [ ] Show a system notification with
    - [ ] Proper logo (Eurofurence wolf badge)
    - [ ] Title and Message of the private message (coming from the FCM payload)
    - [ ] Tapping the notification should...
      - [ ] (at least) ...open the app on the private messages screen
      - [ ] (at best) ...open the private message directly

**Comment by Requinard** [comment]
I think this has been done over the weekend. closing
