### ISSUE TITLE
Dealer tabs are not useful

### ISSUE THREAD

**Issue by lukashaertel** [eurofurence/ef-app_react-native#84]
Almost all dealers attend every day. Therefore displaying by day does not really make sense (at least for our data set). The day filtering can therefore probably be removed, it is the least portable anyway.

**Comment by Pinselohrkater** [comment]
How about providing an "All" Tab (+ Search) and one for the distinct categories?

**Comment by lukashaertel** [comment]
Favorites, all, regular, after dark, classic A tru Z, search bar in all of them
